namespace MonkeFrames.Core.Models;

public struct Transition
{
    // Type of transition to apply
    public TransitionEffect Effect;

    // The amount of time it should take for the transition to apply
    public float Duration;

    // Reverse the transition effect
    public bool Reversed;

    public Transition()
    {
        Effect = TransitionEffect.Unset;
        Duration = -1f;
        Reversed = false;
    }

    public static Transition Linear
    {
        get
        {
            if (field.Effect == TransitionEffect.Unset)
            {
                field = new Transition();

                field.Effect = TransitionEffect.Linear;
                field.Duration = 5f;
                field.Reversed = false;
            }

            return field;
        }
    }

}

public enum TransitionEffect
{
    Unset = -1,

    // Basic direct-line transition.
    Linear = 0,

    // Motion generated by a sine wave to smooth starting and ending.
    Sine,

    // Direct cut. Keyframe will keep it's position until the next one.
    Cut
}