namespace MonkeFrames.Models;

public struct Transition
{
    // Type of transition to apply
    public TransitionEffect Effect;

    // The amount of time it should take for the transition to apply
    public float Duration;

    // Reverse the transition effect
    public bool Reversed;
}

public enum TransitionEffect
{
    // Basic direct-line transition.
    Linear = 0,

    // Motion generated by a sine wave to smooth starting and ending.
    Sine,

    // Direct cut. Keyframe will keep it's position until the next one.
    Cut
}