<?xml version="1.0" encoding="utf-8" ?>
<Project>
	<!-- Invoke as: msbuild MonkeFrames.Editor.csproj /t:FfmpegUpgrade -->
	<Target Name="CopyFilesToBuild" AfterTargets="Build">
		<ItemGroup>
			<AssembliesToCopy Include="$(OutputPath)\MonkeFrames.Compiler.dll" />
			<AssembliesToCopy Include="$(OutputPath)\MonkeFrames.Editor.dll" />
			<AssembliesToCopy Include="$(SolutionDir)Build\Dependencies\ffmpeg\ffmpeg.exe" />
		</ItemGroup>

		<Copy SourceFiles="@(AssembliesToCopy)" DestinationFolder="$(SolutionDir)Build\latest\tmp\BepInEx\plugins\MonkeFrames"/>
		<ZipDirectory
			SourceDirectory="$(SolutionDir)Build\latest\tmp"
			DestinationFile="$(SolutionDir)Build\latest\MonkeFrames.zip"
			Overwrite="true" />

		<RemoveDir Directories="$(SolutionDir)Build\latest\tmp" />
		
		<Message Text="Built MonkeFrames.zip -> Build\latest\tmp" Importance="high"/>
		
		<Copy SourceFiles="@(AssembliesToCopy)" DestinationFolder="$(SolutionDir)Build\latest"/>
		<Message Text="Copied assemblies to build folder -> Build\latest" Importance="high"/>
	</Target>

	<Target Name="InstallToPlugins" AfterTargets="Build">
		<Copy
			  SourceFiles="@(AssembliesToCopy)"
			  DestinationFolder="$(GamePath)\BepInEx\plugins\MonkeFrames\"/>
		
		<Message Text="MonkeFrames installed to plugins" Importance="high"/>
	</Target>
</Project>
