<?xml version="1.0" encoding="utf-8" ?>
<Project>
	<Target Name="CopyFilesToBuild" AfterTargets="Build">
		<ItemGroup>
			<AssembliesToCopy Include="$(OutputPath)\MonkeFrames.Compiler.dll" />
			<AssembliesToCopy Include="$(OutputPath)\MonkeFrames.Editor.dll" />
			<AssembliesToCopy Include="$(DependenciesPath)\ffmpeg\ffmpeg.exe" />
			<AssembliesToCopy Include="$(DependenciesPath)\README.txt" />
		</ItemGroup>
		
		<Copy SourceFiles="@(AssembliesToCopy)" DestinationFolder="$(SolutionDir)Build\latest"/>
		<Message Text="Copied assemblies to build folder -> Build\latest" Importance="high"/>
	</Target>

	<Target Name="InstallToPlugins" AfterTargets="Build">
		<Copy
			  SourceFiles="@(AssembliesToCopy)"
			  DestinationFolder="$(GamePath)\BepInEx\plugins\MonkeFrames\"/>
		
		<Message Text="MonkeFrames installed to plugins" Importance="high"/>
	</Target>
</Project>
